### ISSUE TITLE
New API: using::pkg() inspired by {import}

### ISSUE THREAD

**Issue by MilesMcBain** [anthonynorth/using#2]
The idea being it herds the user toward fully qualifying the using call, which makes for less awkwardness when detecting usage of using in source files.

Detecting usage or using is important for detecting the dependencies using is declaring for use with `renv`, `capsule` etc.

**Comment by MilesMcBain** [comment]
If using is namespaced we will throw a warning.

Existing `using` function will be deprecated.

**Comment by anthonynorth** [comment]
Closed in #3
